export default {
    HANDLE_SYNC: 'HANDLE_SYNC',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK',
    UPDATE_TOKEN: 'UPDATE_TOKEN',
    SET_USER_DETAILS: 'SET_USER_DETAILS',
    SET_ENVIRONMENT: 'SET_ENVIRONMENT',
    // theme actions
    SET_THEME: 'SET_THEME',
    SET_ONBOARDING_DATA: 'SET_ONBOARDING_DATA',

    // event

    SET_EVENT_DETAILS:"SET_EVENT_DETAILS"
}